import { Component, OnDestroy, OnInit } from '@angular/core';

@Component({
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {

  data: Login = {
    email: 'user@example.com',
    password: '123123',
    isRemember: true
  };

  orig_body_class = '';

  constructor() { }

  ngOnInit(): void {
    this.orig_body_class = document.body.className;
    document.body.className = 'bg-gradient-primary';
  }

  ngOnDestroy(): void {
    document.body.className = this.orig_body_class;
  }

}

// Generated by https://quicktype.io

export interface Login {
  email:      string;
  password:   string;
  isRemember: boolean;
}
